### ISSUE TITLE
Migrate to 11ty image

### ISSUE THREAD

**Issue by krzysztofzuraw** [krzysztofzuraw/blog#597]
# Links
- https://www.aleksandrhovhannisyan.com/blog/eleventy-image-plugin/
- https://www.11ty.dev/docs/plugins/image/

# Todo
- [x] Use image shortcode
- [x] Migrate to images in jpg
- [x] Generate 3 width
- [x] Generate 2 imgs: avif & webp + jpg source
- [x] Cache images in cache
- [x] add img shortcode to vs code snippets
- [x] check how is bot working for img compression
